title: "[Contract Verification] <Title>"
labels: ["contract-verification"]
body:
  - type: markdown
    attributes:
      value: |
        ## Check the docs!
        Before proceeding, please check these links for contract verification help:
         - [Verifying contracts using the hardhat-zksync-verify plugin](https://docs.zksync.io/build/tooling/hardhat/hardhat-zksync-verify)
         - [Verifying contracts using the hardhat-zksync-verify-vyper plugin](https://docs.zksync.io/build/tooling/hardhat/hardhat-zksync-verify-vyper)
  - type: input
    id: team
    attributes:
      label: Team or Project
      description: Enter your team or project name (optional)
    validations:
      required: false
  
  - type: input
    id: chain
    attributes:
      label: ZK chain
      description: Enter the network you are working on (e.g. Era, Abstract, etc.)
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - 
        - Testnet
        - Mainnet
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Block Explorer
      options:
        - 
        - ZKsync explorer (e.g. https://explorer.zksync.io)
        - Etherscan (e.g. https://era.zksync.network)
    validations:
      required: true   

  - type: checkboxes
    id: issue-type
    attributes:
      label: Issue Type
      options:
        - label: Plugin
        - label: Block Explorer
    validations:
      required: true
  
  - type: input
    id: contract-address
    attributes:
      label: Contract Address
    validations:
      required: true

  - type: dropdown
    id: compiler-type
    attributes:
      label: Compiler Type
      options:
        - 
        - Single file
        - Multi-part contract
    validations:
      required: true

  - type: input
    id: zksolc-version
    attributes:
      label: zkSolc Version
    validations:
      required: true

  - type: input
    id: solc-version
    attributes:
      label: Solc Version
    validations:
      required: true

  - type: input
    id: contract-name
    attributes:
      label: Contract Name
    validations:
      required: true

  - type: textarea
    id: contract-code
    attributes:
      label: Contract Code
    validations:
      required: true

  - type: textarea
    id: constructor-arguments
    attributes:
      label: Constructor Arguments
    validations:
      required: true

  - type: input
    id: hardhat-verify-plugin-version
    attributes:
      label: Hardhat Verify Plugin Version
      description: (OPTIONAL if you're using the plugin)
    validations:
      required: false

  - type: input
    id: repo-link
    attributes:
      label: Repo Link (Optional)
      description: Though not mandatory, sharing a repository link with a README that details how to replicate the issue and the errors you're encountering will significantly expedite our support process.
    validations:
      required: false
      
  - type: textarea
    id: details
    attributes:
      label: Additional Details
      description: If applicable, please provide any additional details
    validations:
      required: false
