title: "[SDK] <Title>"
labels: ["sdk"]
body:
  - type: markdown
    attributes:
      value: |
        ## Check the docs!
        Before proceeding, please check this link for SDK help:
         - [SDK Documentation](https://sdk.zksync.io/)

  - type: input
    id: team
    attributes:
      label: Team or Project
      description: Enter your team or project name (optional)
    validations:
      required: false
      
  - type: dropdown
    id: type
    attributes:
      label: Select the SDK
      options:
        -
        - JavaScript
        - Python
        - Java
        - Go
        - Swift
        - Rust
    validations:
      required: true

  - type: input
    id: chain
    attributes:
      label: ZK chain
      description: Enter the network you are working on (e.g. Era, Abstract, etc.)
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Testnet
        - Mainnet
    validations:
      required: true
        
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
    validations:
      required: true
  
  - type: textarea
    id: code-example
    attributes:
      label: Code Example
    validations:
      required: true
  
  - type: input
    id: repo-link
    attributes:
      label: Repo Link (Optional)
      description: Though not mandatory, sharing a repository link with a README that details how to replicate the issue and the errors you're encountering will significantly expedite our support process.
    validations:
      required: false
